### ISSUE TITLE
a bug: for when i use php -c ~/myconfig.ini

### ISSUE THREAD

**Issue by bugyak** [daodao97/hyperf-watch#1]
when run php vendor/bin/watch
show this
ERROR Swoole short name have to disable before start server, please set swoole.use_shortname = off into your php.ini.

ok then I copy one php.ini and modify swoole.use_shortname = off
like this

cp -p php.ini myconfig.ini
echo 'swoole.use_shortname = off' >> myconfig.ini
alias phpcli="php -c ~/myconfig.ini"
then
phpcli vendor/bin/watch

it show 
ERROR Swoole short name have to disable before start server, please set swoole.use_shortname = off into your php.ini.

again

but!
phpcli bin/hyperf.php start is success

**Comment by daodao97** [comment]
my local  `swoole` setting
```shell
extension="swoole.so"
swoole.use_shortname = 'Off'
```
Failed to reproduce what you said.

**Comment by bugyak** [comment]
看到你在代码里调用了环境变量的 php 
但是想说的是，我不想修改 php.ini
我先复制一份 php.ini 取名叫 myconfig.ini
因此我定义了一个 phpcli 的 alias
alias phpcli="php -c ~/myconfig.ini"
然后执行 phpcli vendor/bin/watch 你看能否重现

**Comment by daodao97** [comment]
![image](https://user-images.githubusercontent.com/15009280/83349136-08082f80-a365-11ea-8a91-46f8dfdcde0d.png)
不能嘞, 你这个swoole配置层的问题.
